### PR TITLE
Add support for Blender 2.83

### LINKED ISSUE #96: Upgrade for Blender 2.8/2.9/3.0 or later
is planned a version for Blender 2.8 beta

### PR DESCRIPTION
**Pull request by Oxel40**
These are commits that where cherry-picked from the fork by [sburris0](https://github.com/sburris0/collada-exporter-2.8), which is a fork of [artellblender](https://github.com/artellblender/collada-exporter-2.8)'s fork of [collada-exporter](https://github.com/godotengine/collada-exporter) by [godotengine](https://github.com/godotengine).

According to my limited testing and comments made on [sburris0's pull request](https://github.com/artellblender/collada-exporter-2.8/pull/3), e.g. by [aggregate1166877](https://github.com/artellblender/collada-exporter-2.8/pull/3#issuecomment-648987041), will this fix the compatibility issues with Blender 2.83 LTS.

*Bugsquad edit: This closes #96.*

### CODE REVIEW

**Comment by Calinou** [comment]
@akien-mga Should we merge a Blender 2.8 support PR eventually?

**Comment by Francesco149** [comment]
this doesn't seem to apply modifiers to my mesh. anyone having the same issue?

**Comment by Gentle22** [comment]
> this doesn't seem to apply modifiers to my mesh. anyone having the same issue?

Yes indeed, I have the same issue. Modifiers are not applied.

**Comment by Calinou** [comment]
Superseded by https://github.com/godotengine/collada-exporter/pull/131. Thanks for the contribution nonetheless!

**Pull request closed without merging**
