### PR TITLE
Added basic functionality to move objects to center on export per group

### PR DESCRIPTION
**Pull request by lehthanis**
This adds a check box to the export manager that will move each object in a group to the center before exporting it. This functionality seemed like the best way to allow for multiple assets to be modeled in a single .blend file while still being able to export them as if they were their own file with their own 0,0,0 origin.

In my test cases, each group had multiple objects, but they all shared an origin, so every resulting collada file had objects that were sitting at the origin.

functionality implemented is standard bpy.ops.object.location_clear()

### CODE REVIEW

**Comment by akien-mga** [comment]
The code looks good, though shouldn't it be named `Move to Origin`?

**Comment by lehthanis** [comment]
I struggled with that. The origin is the objects. But center is referred to in shift-s cursor to center. Since I'm not moving anything to the objects origin but moving the object to place its origin at center I went with this nomenclature. I can change it if need be though.

**Comment by lehthanis** [comment]
Apply location actually moves the origin to center without moving the geometry.. This moves object AND origin of object to center.

**Comment by akien-mga** [comment]
> I struggled with that. The origin is the objects. But center is referred to in shift-s cursor to center. Since I'm not moving anything to the objects origin but moving the object to place its origin at center I went with this nomenclature. I can change it if need be though.

No, it's fine as is, I just wondered if this was the usual Blender nomenclature for this (I'm not very familiar with Blender nor this exporter myself). Based on your comments, it seems to be the right name :)

Thanks for your work!

**Pull request merged**
